### PR TITLE
updated react react-domm to v16

### PR DESCRIPTION
**Pull request by abdullateef97**

### CODE REVIEW

**Comment by aviaryan** [comment]
Thanks for this.
Can you please make sure to update preact and preact-compat as well?
https://preactjs.com/guide/switching-to-preact
Also, did you test after doing the update? Any issues?

**Comment by abdullateef97** [comment]
done that, no broken changes

**Comment by abdullateef97** [comment]
done

**Comment by aviaryan** [comment]
@abdullateef97 I believe you still need to delete that file because it is seen in the diff.

**Comment by abdullateef97** [comment]
done that already

**Comment by aviaryan** [comment]
Are you able to run it? I see an error when `yarn start` runs.

```sh
ERROR in ./src/components/ProjectLinks/ProjectLinks.jsx
Module not found: Error: Can't resolve 'react/lib/ReactMount' in '/Users/aviaryan/github/showcase/src/components/ProjectLinks'
 @ ./src/components/ProjectLinks/ProjectLinks.jsx 1:296-327
 @ ./src/components/Project/Project.jsx
 @ ./src/screens/Home/Home.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index.jsx

ERROR in ./src/lib/pathResolver.js
Module not found: Error: Can't resolve 'react/lib/ReactMount' in '/Users/aviaryan/github/showcase/src/lib'
 @ ./src/lib/pathResolver.js 1:296-327
 @ ./src/components/ProjectLinks/ProjectLinks.jsx
 @ ./src/components/Project/Project.jsx
 @ ./src/screens/Home/Home.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index.jsx
```

**Comment by aviaryan** [comment]
Maybe we should not do the upgrade after all. I see some breaking changes.

**Comment by aviaryan** [comment]
Closing PR due to inactivity.

**Pull request closed without merging**
